### ISSUE TITLE
GET: Return most-recent message for each conversation for a user

### ISSUE THREAD

**Issue by torch2424** [CECS-478-AuRave/SecureChat#14]
This will help with #12 

We need to allow a GET request that returns something like this

``` javascript
var recentMessages = [
    {
        sender: user2,
        text: "hey there!"
    },
    {
        sender: user43,
        text: "sup!"
    }
]
```

It will be an array of the most recent conversation, for every conversation for a user.

This should be working with authentication, and verifying the sessiontoken, or usertoken from passport, or the facebookSDK

**Comment by kuminin** [comment]
Recent messages can be obtained by getting the conversation and getting the last element from the message list.
