### ISSUE TITLE
GET: Return all messages in a conversation

### ISSUE THREAD

**Issue by torch2424** [CECS-478-AuRave/SecureChat#15]
This will help with #13 

We need to allow a GET request that returns something like this

``` javascript
var convoMessages = [
    {
        sender: user2,
        text: "hey there!",
        time: "12:00PMJSTIMEDATE"
    },
    {
        sender: user43,
        text: "sup!"
        time: "12:01PMJSTIMEDATE"
    },
    {
        sender: user5,
        text: "Group Chat is cool!"
        time: "13:01PMJSTIMEDATE"
    },
]
```

It will be an array of messages in a conversation between all of the users. This does not have to support group chat as of yet, but would be nice to keep that in mind while coding.

This should be working with authentication, and verifying the session token, or user token from passport, or the facebookSDK

**Comment by kuminin** [comment]
Most recent merge to master from #40 allows users to get all messages
