### ISSUE TITLE
Tag Which messages are sent by the user

### ISSUE THREAD

**Issue by torch2424** [CECS-478-AuRave/SecureChat#47]
Currently, our Conversations look like this

``` javascript
var conversationMessage = {

_id: "58098524d914ff5bb9eb4bc1"
date: "2016-10-21T03:01:56.421Z"
from: "Aaron Turner"
message: "Hey, Active Updating is working! I can send a message to the server :^)!!"

}
```

From this model, we do not store the id of the user who sent the message. Thus, I can only do an innacurate check of which user actually sent the message.

I would like to tag or messages with, so I may update out ngFor in the conversation view for messages sent specifically by the user.

**Comment by torch2424** [comment]
Would be a good idea to remove the tag user messages function, and simply compare the ids in the conversations html

**Comment by kuminin** [comment]
``` javascript
var conversationMessage = {

_id: "58098524d_914ff5bb9eb4bc1"
date: "2016-10-21T03:01:56.421Z"
from: {
    Name: "Aaron Turner",
    id: "58098524d",
},
message: "Hey, Active Updating is working! I can send a message to the server :^)!!"

}
```

I can do that if you want the user's facebookID

**Comment by torch2424** [comment]
Yes please :)
