### ISSUE TITLE
For "Already Exists" Error, Please return a 409, Conflict, instead of a 400, Bad Request

### ISSUE THREAD

**Issue by torch2424** [CECS-478-AuRave/SecureChat#57]
http://www.restpatterns.org/HTTP_Status_Codes/409_-_Conflict

There are now multiple places where being able to handle a conversation already exists, would be helpful and make a little more sense in the client. 

For instance, if a user tries to make a new conversation with a user, when the conversation already exists, we should return 409

**Comment by torch2424** [comment]
Actually this is required for #56

**Comment by kuminin** [comment]
Will fix this asap.

**Comment by torch2424** [comment]
Ayyeee :heart:
